		<!-- JavaScript Files -->
		<script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/jquery-migrate-1.2.1.min.js"></script>	
		<script src="js/bootstrap.min.js"></script>
		<script src="js/bootstrap-hover-dropdown.min.js"></script>
		<script src="js/jquery.magnific-popup.min.js"></script>
		<script src="js/dropzone.js"></script>
		<script src="js/validator.js"></script>
		<script src="js/custom.js"></script>