package gui;

import napakalaki.BadConsequence;
import napakalaki.NumericBadConsequence;
import napakalaki.SpecificBadConsequence;

/**
 *
 * @author Carlos de al Torre
 */
public class BadConsequenceView extends javax.swing.JPanel {

    /**
     * Este será el objeto de tipo BadConsequence que tengamos en la vista para
     * preguntarle todos los datos necesarios.
     */
    BadConsequence badconsequenceModel;

    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    /**
     * Con este metodo conseguimos asignar el BadConsequence a la vista para
     * mostrar todos sus atributos.
     *
     * @param aBadConsequence es un objeto de cualquiera de las clases que hay
     * de BadConsequence, ya que lo leera igualmente.
     */
    protected void setBadConsequence(BadConsequence aBadConsequence) {
        this.badconsequenceModel = aBadConsequence;
        this.jTATextoMalRollo.setText(this.badconsequenceModel.getText());
        this.jTNiveles.setText("" + this.badconsequenceModel.getLevels());
        if (this.badconsequenceModel.getDeath()) {
            this.jTMuerte.setText("Si");
        } else {
            this.jTMuerte.setText("No");
        }
        if (this.badconsequenceModel instanceof NumericBadConsequence) {
            this.jTATesorosVisibles.setText(""+((NumericBadConsequence) this.badconsequenceModel).getNVisibleTreasures());
            this.jTATesorosOcultos.setText(""+((NumericBadConsequence) this.badconsequenceModel).getNHiddenTreasures());
        } else if (this.badconsequenceModel instanceof SpecificBadConsequence) {
            this.jTATesorosVisibles.setText(((SpecificBadConsequence) this.badconsequenceModel).getSpecificVisibleTreasures().toString());
            this.jTATesorosOcultos.setText(((SpecificBadConsequence) this.badconsequenceModel).getSpecificHiddenTreasures().toString());
        } else {
            this.jLPierdesTesorosVisibles.setVisible(false);
            this.jLPierdesTesorosOcultos.setVisible(false);
            this.jTATesorosVisibles.setVisible(false);
            this.jTATesorosOcultos.setVisible(false);
        }
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTATesorosOcultos = new javax.swing.JTextArea();
        jLPierdes = new javax.swing.JLabel();
        jTNiveles = new javax.swing.JTextField();
        jLTeMata = new javax.swing.JLabel();
        jTMuerte = new javax.swing.JTextField();
        jLNiveles = new javax.swing.JLabel();
        jTATextoMalRollo = new javax.swing.JTextArea();
        jLPierdesTesorosVisibles = new javax.swing.JLabel();
        jLPierdesTesorosOcultos = new javax.swing.JLabel();
        jTATesorosVisibles = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo del Monstruo"));
        setMinimumSize(new java.awt.Dimension(222, 230));
        setPreferredSize(new java.awt.Dimension(222, 230));
        setRequestFocusEnabled(false);

        jTATesorosOcultos.setBackground(new java.awt.Color(238, 238, 238));
        jTATesorosOcultos.setColumns(9);
        jTATesorosOcultos.setLineWrap(true);
        jTATesorosOcultos.setRows(2);

        jLPierdes.setLabelFor(jTNiveles);
        jLPierdes.setText("Pierdes:");

        jTNiveles.setBackground(new java.awt.Color(238, 238, 238));
        jTNiveles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNiveles.setText("jTNiveles");
        jTNiveles.setBorder(null);

        jLTeMata.setLabelFor(jLPierdes);
        jLTeMata.setText("Te Mata:");

        jTMuerte.setBackground(new java.awt.Color(238, 238, 238));
        jTMuerte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTMuerte.setText("jTMuerte");
        jTMuerte.setBorder(null);

        jLNiveles.setLabelFor(jLPierdes);
        jLNiveles.setText("niveles");

        jTATextoMalRollo.setBackground(new java.awt.Color(238, 238, 238));
        jTATextoMalRollo.setColumns(9);
        jTATextoMalRollo.setLineWrap(true);
        jTATextoMalRollo.setRows(4);
        jTATextoMalRollo.setBorder(null);

        jLPierdesTesorosVisibles.setLabelFor(jTATesorosOcultos);
        jLPierdesTesorosVisibles.setText("Pierdes Tesoros Visibles:");

        jLPierdesTesorosOcultos.setLabelFor(jTATesorosOcultos);
        jLPierdesTesorosOcultos.setText("Pierdes Tesoros Ocultos:");

        jTATesorosVisibles.setBackground(new java.awt.Color(238, 238, 238));
        jTATesorosVisibles.setColumns(9);
        jTATesorosVisibles.setLineWrap(true);
        jTATesorosVisibles.setRows(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTATextoMalRollo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLPierdesTesorosVisibles)
                                .addComponent(jLPierdesTesorosOcultos)
                                .addComponent(jTATesorosVisibles)
                                .addComponent(jTATesorosOcultos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLPierdes)
                                    .addComponent(jLTeMata))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTMuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLNiveles)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTATextoMalRollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPierdes)
                    .addComponent(jTNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNiveles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTeMata)
                    .addComponent(jTMuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPierdesTesorosVisibles)
                .addGap(0, 0, 0)
                .addComponent(jTATesorosVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPierdesTesorosOcultos)
                .addGap(0, 0, 0)
                .addComponent(jTATesorosOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLNiveles;
    private javax.swing.JLabel jLPierdes;
    private javax.swing.JLabel jLPierdesTesorosOcultos;
    private javax.swing.JLabel jLPierdesTesorosVisibles;
    private javax.swing.JLabel jLTeMata;
    private javax.swing.JTextArea jTATesorosOcultos;
    private javax.swing.JTextArea jTATesorosVisibles;
    private javax.swing.JTextArea jTATextoMalRollo;
    private javax.swing.JTextField jTMuerte;
    private javax.swing.JTextField jTNiveles;
    // End of variables declaration//GEN-END:variables
}
