package gui;

import napakalaki.Prize;

/**
 *
 * @author Carlos de al Torre
 */
public class PrizeView extends javax.swing.JPanel {

    /**
     * Este será el objeto de tipo Prize que tengamos en la vista para
     * preguntarle todos los datos necesarios.
     */
    Prize prizeModel;

    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

    /**
     * Con este metodo conseguimos asignar el Prize a la vista para mostrar
     * todos sus atributos.
     *
     * @param aPrice es un objeto Prize que lo pedimos al controlador.
     */
    protected void setPrize(Prize aPrice) {
        this.prizeModel = aPrice;
        int tesoros = this.prizeModel.getTreasures(), niveles = this.prizeModel.getLevels();
        switch (tesoros) {
            case 0:
                this.jLTesoros.setText("No Ganas Tesoros");
                break;
            case 1:
                this.jLTesoros.setText("Puedes Ganar: " + tesoros + " Tesoro");
                break;
            default:
                this.jLTesoros.setText("Puedes Ganar: " + tesoros + " Tesoros");
                break;
        }
        switch (niveles) {
            case 0:
                this.jLNiveles.setText("No Ganas Niveles");
                break;
            case 1:
                this.jLNiveles.setText("Puedes Ganar: " + niveles + " Nivel");
                break;
            default:
                this.jLNiveles.setText("Puedes Ganar: " + niveles + " Niveles");
                break;
        }
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTesoros = new javax.swing.JLabel();
        jLNiveles = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Ganancias"));
        setMinimumSize(new java.awt.Dimension(222, 100));
        setPreferredSize(new java.awt.Dimension(222, 100));

        jLTesoros.setText("Puedes Ganar: X Tesoros");

        jLNiveles.setText("Puedes Ganar: X Niveles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLTesoros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLNiveles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTesoros)
                .addGap(18, 18, 18)
                .addComponent(jLNiveles)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLNiveles;
    private javax.swing.JLabel jLTesoros;
    // End of variables declaration//GEN-END:variables
}
