/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.others;

import javax.swing.ImageIcon;
import sm.cdlt.util.Utils;

/**
 *
 * @author Carlos de al Torre
 */
public class Splash extends java.awt.Window {

    /**
     * Esta será la imagen que queremos mostrar.
     */
    ImageIcon miImage = null;

    public Splash(java.awt.Window owner) {
        super(owner);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(792, 495));
        setPreferredSize(new java.awt.Dimension(792, 495));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/huevo.jpg"))); // NOI18N
        add(jLabelImagen, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        dispose();
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    // End of variables declaration//GEN-END:variables
}
