package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JSlider;
import javax.swing.JToolBar;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import practica3.Lienzo;

/**
 *
 * @author Carlos de al Torre
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBar = new JPanel();
        jPanelOptionBar = new JPanel();
        jToolBarHerramientas = new JToolBar();
        jButtonPunto = new JButton();
        jPanelStatusBar = new JPanel();
        jLabelVerMensajes = new JLabel();
        jPanelCentral = new JPanel();
        jPanelLienzo = new Lienzo();
        jPanelUtiles = new JPanel();
        filler2 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jButtonNegro = new JButton();
        filler3 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jButtonBlanco = new JButton();
        filler4 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jButtonRojo = new JButton();
        filler5 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jButtonVerde = new JButton();
        filler6 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jButtonAzul = new JButton();
        filler7 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jButtonAmarillo = new JButton();
        filler8 = new Box.Filler(new Dimension(30, 0), new Dimension(30, 0), new Dimension(30, 32767));
        jLabelGrosorEtiqueta = new JLabel();
        filler11 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jLabel1Grosor = new JLabel();
        filler10 = new Box.Filler(new Dimension(5, 0), new Dimension(5, 0), new Dimension(5, 32767));
        jSliderGrosor = new JSlider();
        filler12 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 0));
        jCheckBoxRelleno = new JCheckBox();
        filler1 = new Box.Filler(new Dimension(10, 0), new Dimension(10, 0), new Dimension(10, 32767));
        jMenuBarra = new JMenuBar();
        jMenuArchivo = new JMenu();
        jMenuItemNuevo = new JMenuItem();
        jMenuItemAbrir = new JMenuItem();
        jMenuItemGuardar = new JMenuItem();
        jSeparator1MArchivo = new JPopupMenu.Separator();
        jMenuItemSalir = new JMenuItem();
        jMenuEditar = new JMenu();
        jMenuItemCortar = new JMenuItem();
        jMenuItemCopiar = new JMenuItem();
        jMenuItemPegar = new JMenuItem();
        jMenuVer = new JMenu();
        jCheckBoxMenuItemVerBarraMenu = new JCheckBoxMenuItem();
        jCheckBoxMenuItemVerBarraHerramientas = new JCheckBoxMenuItem();
        jCheckBoxMenuItemVerBarraEstado = new JCheckBoxMenuItem();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Básico");
        setMinimumSize(new Dimension(300, 300));
        setPreferredSize(new Dimension(700, 500));

        jPanelToolBar.setLayout(null);
        getContentPane().add(jPanelToolBar, BorderLayout.LINE_START);

        jPanelOptionBar.setLayout(null);
        getContentPane().add(jPanelOptionBar, BorderLayout.LINE_END);

        jToolBarHerramientas.setRollover(true);
        jToolBarHerramientas.setToolTipText("Herramientas que puedes usar");
        jToolBarHerramientas.setMaximumSize(new Dimension(150, 32));
        jToolBarHerramientas.setMinimumSize(new Dimension(150, 32));
        jToolBarHerramientas.setName("Herramientas"); // NOI18N
        jToolBarHerramientas.setPreferredSize(new Dimension(150, 32));

        jButtonPunto.setText("Punto");
        jButtonPunto.setFocusable(false);
        jButtonPunto.setHorizontalTextPosition(SwingConstants.CENTER);
        jButtonPunto.setVerticalTextPosition(SwingConstants.BOTTOM);
        jButtonPunto.addActionListener(formListener);
        jToolBarHerramientas.add(jButtonPunto);

        getContentPane().add(jToolBarHerramientas, BorderLayout.PAGE_START);

        jPanelStatusBar.setBorder(BorderFactory.createEtchedBorder());
        jPanelStatusBar.setLayout(new BoxLayout(jPanelStatusBar, BoxLayout.LINE_AXIS));

        jLabelVerMensajes.setText("Mensajes");
        jLabelVerMensajes.setMaximumSize(null);
        jLabelVerMensajes.setMinimumSize(new Dimension(50, 25));
        jLabelVerMensajes.setPreferredSize(new Dimension(50, 25));
        jPanelStatusBar.add(jLabelVerMensajes);

        getContentPane().add(jPanelStatusBar, BorderLayout.PAGE_END);

        jPanelCentral.setLayout(new BorderLayout());

        jPanelLienzo.setBackground(new Color(255, 255, 255));
        jPanelLienzo.addMouseMotionListener(formListener);
        jPanelLienzo.addMouseListener(formListener);
        jPanelLienzo.setLayout(null);
        jPanelCentral.add(jPanelLienzo, BorderLayout.CENTER);

        jPanelUtiles.setMinimumSize(new Dimension(469, 30));
        jPanelUtiles.setPreferredSize(new Dimension(569, 30));
        jPanelUtiles.setLayout(new BoxLayout(jPanelUtiles, BoxLayout.LINE_AXIS));
        jPanelUtiles.add(filler2);

        jButtonNegro.setBackground(new Color(0, 0, 0));
        jButtonNegro.setBorder(BorderFactory.createEtchedBorder());
        jButtonNegro.setBorderPainted(false);
        jButtonNegro.setMaximumSize(new Dimension(20, 20));
        jButtonNegro.setMinimumSize(new Dimension(20, 20));
        jButtonNegro.setPreferredSize(new Dimension(20, 20));
        jButtonNegro.addActionListener(formListener);
        jPanelUtiles.add(jButtonNegro);
        jPanelUtiles.add(filler3);

        jButtonBlanco.setBackground(new Color(255, 255, 255));
        jButtonBlanco.setBorder(BorderFactory.createEtchedBorder());
        jButtonBlanco.setBorderPainted(false);
        jButtonBlanco.setMaximumSize(new Dimension(20, 20));
        jButtonBlanco.setMinimumSize(new Dimension(20, 20));
        jButtonBlanco.setPreferredSize(new Dimension(20, 20));
        jButtonBlanco.addActionListener(formListener);
        jPanelUtiles.add(jButtonBlanco);
        jPanelUtiles.add(filler4);

        jButtonRojo.setBackground(new Color(255, 0, 0));
        jButtonRojo.setBorder(BorderFactory.createEtchedBorder());
        jButtonRojo.setBorderPainted(false);
        jButtonRojo.setMaximumSize(new Dimension(20, 20));
        jButtonRojo.setMinimumSize(new Dimension(20, 20));
        jButtonRojo.setPreferredSize(new Dimension(20, 20));
        jButtonRojo.addActionListener(formListener);
        jPanelUtiles.add(jButtonRojo);
        jPanelUtiles.add(filler5);

        jButtonVerde.setBackground(new Color(0, 255, 0));
        jButtonVerde.setBorder(BorderFactory.createEtchedBorder());
        jButtonVerde.setBorderPainted(false);
        jButtonVerde.setMaximumSize(new Dimension(20, 20));
        jButtonVerde.setMinimumSize(new Dimension(20, 20));
        jButtonVerde.setPreferredSize(new Dimension(20, 20));
        jButtonVerde.addActionListener(formListener);
        jPanelUtiles.add(jButtonVerde);
        jPanelUtiles.add(filler6);

        jButtonAzul.setBackground(new Color(0, 0, 255));
        jButtonAzul.setBorder(BorderFactory.createEtchedBorder());
        jButtonAzul.setBorderPainted(false);
        jButtonAzul.setMaximumSize(new Dimension(20, 20));
        jButtonAzul.setMinimumSize(new Dimension(20, 20));
        jButtonAzul.setPreferredSize(new Dimension(20, 20));
        jButtonAzul.addActionListener(formListener);
        jPanelUtiles.add(jButtonAzul);
        jPanelUtiles.add(filler7);

        jButtonAmarillo.setBackground(new Color(255, 255, 0));
        jButtonAmarillo.setBorder(BorderFactory.createEtchedBorder());
        jButtonAmarillo.setBorderPainted(false);
        jButtonAmarillo.setMaximumSize(new Dimension(20, 20));
        jButtonAmarillo.setMinimumSize(new Dimension(20, 20));
        jButtonAmarillo.setPreferredSize(new Dimension(20, 20));
        jButtonAmarillo.addActionListener(formListener);
        jPanelUtiles.add(jButtonAmarillo);
        jPanelUtiles.add(filler8);

        jLabelGrosorEtiqueta.setFont(new Font("Dialog", 1, 14)); // NOI18N
        jLabelGrosorEtiqueta.setText("Grosor:");
        jPanelUtiles.add(jLabelGrosorEtiqueta);
        jPanelUtiles.add(filler11);

        jLabel1Grosor.setText("4");
        jLabel1Grosor.setMaximumSize(new Dimension(25, 15));
        jLabel1Grosor.setMinimumSize(new Dimension(25, 15));
        jLabel1Grosor.setPreferredSize(new Dimension(25, 15));
        jPanelUtiles.add(jLabel1Grosor);
        jPanelUtiles.add(filler10);

        jSliderGrosor.setMinimum(4);
        jSliderGrosor.setMinorTickSpacing(1);
        jSliderGrosor.setPaintLabels(true);
        jSliderGrosor.setToolTipText("Este es el grosor que tendra la linea de la herramienta");
        jSliderGrosor.setValue(4);
        jSliderGrosor.setMaximumSize(new Dimension(300, 16));
        jSliderGrosor.setMinimumSize(new Dimension(100, 16));
        jSliderGrosor.addChangeListener(formListener);
        jPanelUtiles.add(jSliderGrosor);
        jPanelUtiles.add(filler12);

        jCheckBoxRelleno.setFont(new Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxRelleno.setText("Relleno");
        jCheckBoxRelleno.addActionListener(formListener);
        jPanelUtiles.add(jCheckBoxRelleno);
        jPanelUtiles.add(filler1);

        jPanelCentral.add(jPanelUtiles, BorderLayout.SOUTH);

        getContentPane().add(jPanelCentral, BorderLayout.CENTER);

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevo.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_MASK));
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.setToolTipText("");
        jMenuItemNuevo.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuItemAbrir.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.CTRL_MASK));
        jMenuItemAbrir.setText("Abrir...");
        jMenuItemAbrir.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemAbrir);

        jMenuItemGuardar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_MASK));
        jMenuItemGuardar.setText("Guardar...");
        jMenuItemGuardar.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemGuardar);

        jSeparator1MArchivo.setMinimumSize(new Dimension(10, 10));
        jMenuArchivo.add(jSeparator1MArchivo);

        jMenuItemSalir.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Q, InputEvent.CTRL_MASK));
        jMenuItemSalir.setText("Salir...");
        jMenuItemSalir.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBarra.add(jMenuArchivo);

        jMenuEditar.setText("Editar");

        jMenuItemCortar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X, InputEvent.CTRL_MASK));
        jMenuItemCortar.setText("Cortar");
        jMenuItemCortar.addActionListener(formListener);
        jMenuEditar.add(jMenuItemCortar);

        jMenuItemCopiar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK));
        jMenuItemCopiar.setText("Copiar");
        jMenuItemCopiar.addActionListener(formListener);
        jMenuEditar.add(jMenuItemCopiar);

        jMenuItemPegar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.CTRL_MASK));
        jMenuItemPegar.setText("Pegar");
        jMenuItemPegar.addActionListener(formListener);
        jMenuEditar.add(jMenuItemPegar);

        jMenuBarra.add(jMenuEditar);

        jMenuVer.setText("Ver");

        jCheckBoxMenuItemVerBarraMenu.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_M, InputEvent.ALT_MASK | InputEvent.CTRL_MASK));
        jCheckBoxMenuItemVerBarraMenu.setSelected(true);
        jCheckBoxMenuItemVerBarraMenu.setText("Barra de Menus");
        jCheckBoxMenuItemVerBarraMenu.addActionListener(formListener);
        jMenuVer.add(jCheckBoxMenuItemVerBarraMenu);

        jCheckBoxMenuItemVerBarraHerramientas.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_T, InputEvent.ALT_MASK | InputEvent.CTRL_MASK));
        jCheckBoxMenuItemVerBarraHerramientas.setSelected(true);
        jCheckBoxMenuItemVerBarraHerramientas.setText("Barra de Herramientas");
        jCheckBoxMenuItemVerBarraHerramientas.addActionListener(formListener);
        jMenuVer.add(jCheckBoxMenuItemVerBarraHerramientas);

        jCheckBoxMenuItemVerBarraEstado.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E, InputEvent.ALT_MASK | InputEvent.CTRL_MASK));
        jCheckBoxMenuItemVerBarraEstado.setSelected(true);
        jCheckBoxMenuItemVerBarraEstado.setText("Barra de Estado");
        jCheckBoxMenuItemVerBarraEstado.addActionListener(formListener);
        jMenuVer.add(jCheckBoxMenuItemVerBarraEstado);

        jMenuBarra.add(jMenuVer);

        setJMenuBar(jMenuBarra);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener, MouseListener, MouseMotionListener, ChangeListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == jButtonNegro) {
                VentanaPrincipal.this.jButtonNegroActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonBlanco) {
                VentanaPrincipal.this.jButtonBlancoActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonRojo) {
                VentanaPrincipal.this.jButtonRojoActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonVerde) {
                VentanaPrincipal.this.jButtonVerdeActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonAzul) {
                VentanaPrincipal.this.jButtonAzulActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonAmarillo) {
                VentanaPrincipal.this.jButtonAmarilloActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxRelleno) {
                VentanaPrincipal.this.jCheckBoxRellenoActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemNuevo) {
                VentanaPrincipal.this.jMenuItemNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemAbrir) {
                VentanaPrincipal.this.jMenuItemAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemGuardar) {
                VentanaPrincipal.this.jMenuItemGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemSalir) {
                VentanaPrincipal.this.jMenuItemSalirActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemCortar) {
                VentanaPrincipal.this.jMenuItemCortarActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemCopiar) {
                VentanaPrincipal.this.jMenuItemCopiarActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemPegar) {
                VentanaPrincipal.this.jMenuItemPegarActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxMenuItemVerBarraMenu) {
                VentanaPrincipal.this.jCheckBoxMenuItemVerBarraMenuActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxMenuItemVerBarraHerramientas) {
                VentanaPrincipal.this.jCheckBoxMenuItemVerBarraHerramientasActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxMenuItemVerBarraEstado) {
                VentanaPrincipal.this.jCheckBoxMenuItemVerBarraEstadoActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonPunto) {
                VentanaPrincipal.this.jButtonPuntoActionPerformed(evt);
            }
        }

        public void mouseClicked(MouseEvent evt) {
            if (evt.getSource() == jPanelLienzo) {
                VentanaPrincipal.this.jPanelLienzoMouseClicked(evt);
            }
        }

        public void mouseEntered(MouseEvent evt) {
        }

        public void mouseExited(MouseEvent evt) {
        }

        public void mousePressed(MouseEvent evt) {
            if (evt.getSource() == jPanelLienzo) {
                VentanaPrincipal.this.jPanelLienzoMousePressed(evt);
            }
        }

        public void mouseReleased(MouseEvent evt) {
        }

        public void mouseDragged(MouseEvent evt) {
            if (evt.getSource() == jPanelLienzo) {
                VentanaPrincipal.this.jPanelLienzoMouseDragged(evt);
            }
        }

        public void mouseMoved(MouseEvent evt) {
        }

        public void stateChanged(ChangeEvent evt) {
            if (evt.getSource() == jSliderGrosor) {
                VentanaPrincipal.this.jSliderGrosorStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        jPanelLienzo.setTool("");
        repaint();
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemAbrirActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jMenuItemGuardarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemSalirActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCortarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemCortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCortarActionPerformed

    private void jMenuItemCopiarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCopiarActionPerformed

    private void jMenuItemPegarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItemPegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPegarActionPerformed

    private void jCheckBoxMenuItemVerBarraMenuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemVerBarraMenuActionPerformed
        this.jMenuBarra.setVisible(this.jCheckBoxMenuItemVerBarraMenu.isSelected());
    }//GEN-LAST:event_jCheckBoxMenuItemVerBarraMenuActionPerformed

    private void jCheckBoxMenuItemVerBarraHerramientasActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemVerBarraHerramientasActionPerformed
        this.jToolBarHerramientas.setVisible(this.jCheckBoxMenuItemVerBarraHerramientas.isSelected());
    }//GEN-LAST:event_jCheckBoxMenuItemVerBarraHerramientasActionPerformed

    private void jCheckBoxMenuItemVerBarraEstadoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemVerBarraEstadoActionPerformed
        this.jPanelStatusBar.setVisible(this.jCheckBoxMenuItemVerBarraEstado.isSelected());
    }//GEN-LAST:event_jCheckBoxMenuItemVerBarraEstadoActionPerformed

    private void jSliderGrosorStateChanged(ChangeEvent evt) {//GEN-FIRST:event_jSliderGrosorStateChanged
        this.jLabel1Grosor.setText(""+this.jSliderGrosor.getValue());
        this.jPanelLienzo.setSize(this.jSliderGrosor.getValue());
    }//GEN-LAST:event_jSliderGrosorStateChanged

    private void jButtonNegroActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonNegroActionPerformed
        jPanelLienzo.setColor(Color.black);
    }//GEN-LAST:event_jButtonNegroActionPerformed

    private void jButtonBlancoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonBlancoActionPerformed
        jPanelLienzo.setColor(Color.white);
    }//GEN-LAST:event_jButtonBlancoActionPerformed

    private void jButtonRojoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonRojoActionPerformed
        jPanelLienzo.setColor(Color.red);
    }//GEN-LAST:event_jButtonRojoActionPerformed

    private void jButtonVerdeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonVerdeActionPerformed
        jPanelLienzo.setColor(Color.green);
    }//GEN-LAST:event_jButtonVerdeActionPerformed

    private void jButtonAzulActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonAzulActionPerformed
        jPanelLienzo.setColor(Color.blue);
    }//GEN-LAST:event_jButtonAzulActionPerformed

    private void jButtonAmarilloActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonAmarilloActionPerformed
        jPanelLienzo.setColor(Color.yellow);
    }//GEN-LAST:event_jButtonAmarilloActionPerformed
    
    private void jPanelLienzoMouseClicked(MouseEvent evt) {//GEN-FIRST:event_jPanelLienzoMouseClicked
        jPanelLienzo.setTool("point");
        jPanelLienzo.setBegin(evt.getPoint());
        repaint();
    }//GEN-LAST:event_jPanelLienzoMouseClicked
    
    private void jPanelLienzoMousePressed(MouseEvent evt) {//GEN-FIRST:event_jPanelLienzoMousePressed
        jPanelLienzo.setTool("line");
        jPanelLienzo.setBegin(evt.getPoint());
        repaint();
    }//GEN-LAST:event_jPanelLienzoMousePressed

    private void jPanelLienzoMouseDragged(MouseEvent evt) {//GEN-FIRST:event_jPanelLienzoMouseDragged
        jPanelLienzo.setEnd(evt.getPoint());
        repaint();
    }//GEN-LAST:event_jPanelLienzoMouseDragged

    private void jCheckBoxRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRellenoActionPerformed
        jPanelLienzo.setFill(this.jCheckBoxRelleno.isSelected());
    }//GEN-LAST:event_jCheckBoxRellenoActionPerformed

    private void jButtonPuntoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonPuntoActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, "hemos pulsado el botón");
    }//GEN-LAST:event_jButtonPuntoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Box.Filler filler1;
    private Box.Filler filler10;
    private Box.Filler filler11;
    private Box.Filler filler12;
    private Box.Filler filler2;
    private Box.Filler filler3;
    private Box.Filler filler4;
    private Box.Filler filler5;
    private Box.Filler filler6;
    private Box.Filler filler7;
    private Box.Filler filler8;
    private JButton jButtonAmarillo;
    private JButton jButtonAzul;
    private JButton jButtonBlanco;
    private JButton jButtonNegro;
    private JButton jButtonPunto;
    private JButton jButtonRojo;
    private JButton jButtonVerde;
    private JCheckBoxMenuItem jCheckBoxMenuItemVerBarraEstado;
    private JCheckBoxMenuItem jCheckBoxMenuItemVerBarraHerramientas;
    private JCheckBoxMenuItem jCheckBoxMenuItemVerBarraMenu;
    private JCheckBox jCheckBoxRelleno;
    private JLabel jLabel1Grosor;
    private JLabel jLabelGrosorEtiqueta;
    private JLabel jLabelVerMensajes;
    private JMenu jMenuArchivo;
    private JMenuBar jMenuBarra;
    private JMenu jMenuEditar;
    private JMenuItem jMenuItemAbrir;
    private JMenuItem jMenuItemCopiar;
    private JMenuItem jMenuItemCortar;
    private JMenuItem jMenuItemGuardar;
    private JMenuItem jMenuItemNuevo;
    private JMenuItem jMenuItemPegar;
    private JMenuItem jMenuItemSalir;
    private JMenu jMenuVer;
    private JPanel jPanelCentral;
    private Lienzo jPanelLienzo;
    private JPanel jPanelOptionBar;
    private JPanel jPanelStatusBar;
    private JPanel jPanelToolBar;
    private JPanel jPanelUtiles;
    private JPopupMenu.Separator jSeparator1MArchivo;
    private JSlider jSliderGrosor;
    private JToolBar jToolBarHerramientas;
    // End of variables declaration//GEN-END:variables
}
