VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "virtualbox"
    config.vm.box="generic/fedora29"
    # Para que esta linea funcione es necesario instalar el plugin de vagrant
    # Con esta linea sincronizamos el directorio de desarrollo con la maquina virtuaĺ
    # vagrant plugin install vagrant-vbguest
    config.vm.synced_folder 'src/', '/home/vagrant/src', SharedFoldersEnableSymlinksCreate: false, disabled: true
    config.vm.communicator = "ssh"
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    #config.ssh.private_key_path = "~/.ssh/id_rsa_deploying"
    config.vm.hostname = "develop-machine"
    config.vm.network "forwarded_port", guest: 5000, host: 8080

    # Provisionamiento con ansible
    config.vm.provision :ansible do |ansible|
        ansible.playbook = "./provision/playbook.yml"
    end
end
