package gui;

import java.awt.Color;
import java.awt.event.MouseWheelEvent;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Carlos de al Torre
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTools = new javax.swing.ButtonGroup();
        jToolBarTools = new javax.swing.JToolBar();
        jToggleButtonPunto = new javax.swing.JToggleButton();
        jToggleButtonLinea = new javax.swing.JToggleButton();
        jToggleButtonRectangulo = new javax.swing.JToggleButton();
        jToggleButtonCirculo = new javax.swing.JToggleButton();
        jPanelStatusBar = new javax.swing.JPanel();
        jLabelHerramienta = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jLabelColor = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jPanelUtils = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButtonNegro = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButtonBlanco = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButtonRojo = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButtonVerde = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButtonAzul = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jButtonAmarillo = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 32767));
        jLabelGrosorEtiqueta = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jLabelGrosor = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jSliderGrosor = new javax.swing.JSlider();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jCheckBoxRelleno = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanelLienzo = new practica4.Lienzo();
        jMenuBarra = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jSeparator1MArchivo = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemCortar = new javax.swing.JMenuItem();
        jMenuItemCopiar = new javax.swing.JMenuItem();
        jMenuItemPegar = new javax.swing.JMenuItem();
        jMenuVer = new javax.swing.JMenu();
        jCheckBoxMenuItemVerBarraHerramientas = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemVerBarraMenu = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemVerBarraEstado = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItemPantallaCompleta = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Básico");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(700, 600));

        jToolBarTools.setRollover(true);
        jToolBarTools.setToolTipText("Herramientas que puedes usar");
        jToolBarTools.setMaximumSize(new java.awt.Dimension(150, 32));
        jToolBarTools.setMinimumSize(new java.awt.Dimension(150, 32));
        jToolBarTools.setName("Herramientas"); // NOI18N
        jToolBarTools.setPreferredSize(new java.awt.Dimension(150, 32));

        GroupTools.add(jToggleButtonPunto);
        jToggleButtonPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/punto.png"))); // NOI18N
        jToggleButtonPunto.setSelected(true);
        jToggleButtonPunto.setFocusable(false);
        jToggleButtonPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonPunto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonPunto.addActionListener(formListener);
        jToolBarTools.add(jToggleButtonPunto);
        jToggleButtonPunto.getAccessibleContext().setAccessibleName("Punto");
        jToggleButtonPunto.getAccessibleContext().setAccessibleDescription("Herramienta Punto");

        GroupTools.add(jToggleButtonLinea);
        jToggleButtonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/linea.png"))); // NOI18N
        jToggleButtonLinea.setFocusable(false);
        jToggleButtonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonLinea.addActionListener(formListener);
        jToolBarTools.add(jToggleButtonLinea);

        GroupTools.add(jToggleButtonRectangulo);
        jToggleButtonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rectangulo.png"))); // NOI18N
        jToggleButtonRectangulo.setFocusable(false);
        jToggleButtonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonRectangulo.addActionListener(formListener);
        jToolBarTools.add(jToggleButtonRectangulo);

        GroupTools.add(jToggleButtonCirculo);
        jToggleButtonCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        jToggleButtonCirculo.setFocusable(false);
        jToggleButtonCirculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonCirculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonCirculo.addActionListener(formListener);
        jToolBarTools.add(jToggleButtonCirculo);

        getContentPane().add(jToolBarTools, java.awt.BorderLayout.PAGE_START);

        jPanelStatusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelStatusBar.setLayout(new javax.swing.BoxLayout(jPanelStatusBar, javax.swing.BoxLayout.LINE_AXIS));

        jLabelHerramienta.setText("Herramienta: Punto");
        jLabelHerramienta.setMaximumSize(new java.awt.Dimension(250, 25));
        jLabelHerramienta.setMinimumSize(new java.awt.Dimension(150, 25));
        jLabelHerramienta.setPreferredSize(new java.awt.Dimension(225, 25));
        jPanelStatusBar.add(jLabelHerramienta);
        jPanelStatusBar.add(filler9);

        jLabelColor.setText("Color: Negro");
        jLabelColor.setMaximumSize(new java.awt.Dimension(150, 25));
        jLabelColor.setMinimumSize(new java.awt.Dimension(75, 25));
        jLabelColor.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanelStatusBar.add(jLabelColor);

        getContentPane().add(jPanelStatusBar, java.awt.BorderLayout.PAGE_END);

        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jPanelUtils.setMinimumSize(new java.awt.Dimension(469, 30));
        jPanelUtils.setPreferredSize(new java.awt.Dimension(569, 30));
        jPanelUtils.setLayout(new javax.swing.BoxLayout(jPanelUtils, javax.swing.BoxLayout.LINE_AXIS));
        jPanelUtils.add(filler2);

        jButtonNegro.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNegro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNegro.setBorderPainted(false);
        jButtonNegro.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonNegro.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonNegro.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonNegro.addActionListener(formListener);
        jPanelUtils.add(jButtonNegro);
        jPanelUtils.add(filler3);

        jButtonBlanco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBlanco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBlanco.setBorderPainted(false);
        jButtonBlanco.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonBlanco.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonBlanco.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonBlanco.addActionListener(formListener);
        jPanelUtils.add(jButtonBlanco);
        jPanelUtils.add(filler4);

        jButtonRojo.setBackground(new java.awt.Color(255, 0, 0));
        jButtonRojo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonRojo.setBorderPainted(false);
        jButtonRojo.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonRojo.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonRojo.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonRojo.addActionListener(formListener);
        jPanelUtils.add(jButtonRojo);
        jPanelUtils.add(filler5);

        jButtonVerde.setBackground(new java.awt.Color(0, 255, 0));
        jButtonVerde.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonVerde.setBorderPainted(false);
        jButtonVerde.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonVerde.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonVerde.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonVerde.addActionListener(formListener);
        jPanelUtils.add(jButtonVerde);
        jPanelUtils.add(filler6);

        jButtonAzul.setBackground(new java.awt.Color(0, 0, 255));
        jButtonAzul.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAzul.setBorderPainted(false);
        jButtonAzul.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonAzul.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonAzul.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonAzul.addActionListener(formListener);
        jPanelUtils.add(jButtonAzul);
        jPanelUtils.add(filler7);

        jButtonAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        jButtonAmarillo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAmarillo.setBorderPainted(false);
        jButtonAmarillo.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonAmarillo.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonAmarillo.setPreferredSize(new java.awt.Dimension(20, 20));
        jButtonAmarillo.addActionListener(formListener);
        jPanelUtils.add(jButtonAmarillo);
        jPanelUtils.add(filler8);

        jLabelGrosorEtiqueta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelGrosorEtiqueta.setLabelFor(jSliderGrosor);
        jLabelGrosorEtiqueta.setText("Grosor:");
        jLabelGrosorEtiqueta.addMouseWheelListener(formListener);
        jPanelUtils.add(jLabelGrosorEtiqueta);
        jPanelUtils.add(filler11);

        jLabelGrosor.setText("4");
        jLabelGrosor.setMaximumSize(new java.awt.Dimension(25, 15));
        jLabelGrosor.setMinimumSize(new java.awt.Dimension(25, 15));
        jLabelGrosor.setPreferredSize(new java.awt.Dimension(25, 15));
        jLabelGrosor.addMouseWheelListener(formListener);
        jPanelUtils.add(jLabelGrosor);
        jPanelUtils.add(filler10);

        jSliderGrosor.setMinimum(4);
        jSliderGrosor.setMinorTickSpacing(1);
        jSliderGrosor.setPaintLabels(true);
        jSliderGrosor.setToolTipText("Este es el grosor que tendra la linea de la herramienta");
        jSliderGrosor.setValue(4);
        jSliderGrosor.setMaximumSize(new java.awt.Dimension(300, 16));
        jSliderGrosor.setMinimumSize(new java.awt.Dimension(100, 16));
        jSliderGrosor.addChangeListener(formListener);
        jSliderGrosor.addMouseWheelListener(formListener);
        jPanelUtils.add(jSliderGrosor);
        jPanelUtils.add(filler12);

        jCheckBoxRelleno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBoxRelleno.setText("Relleno");
        jCheckBoxRelleno.addActionListener(formListener);
        jPanelUtils.add(jCheckBoxRelleno);
        jPanelUtils.add(filler1);

        jPanelCenter.add(jPanelUtils, java.awt.BorderLayout.SOUTH);

        jPanelLienzo.addMouseMotionListener(formListener);
        jPanelLienzo.addMouseListener(formListener);
        jPanelCenter.add(jPanelLienzo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nuevo.png"))); // NOI18N
        jMenuItemNuevo.setText("Nuevo");
        jMenuItemNuevo.setToolTipText("");
        jMenuItemNuevo.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/abrir.png"))); // NOI18N
        jMenuItemAbrir.setText("Abrir...");
        jMenuItemAbrir.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemAbrir);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guardar.png"))); // NOI18N
        jMenuItemGuardar.setText("Guardar...");
        jMenuItemGuardar.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemGuardar);

        jSeparator1MArchivo.setMinimumSize(new java.awt.Dimension(10, 10));
        jMenuArchivo.add(jSeparator1MArchivo);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salir.png"))); // NOI18N
        jMenuItemSalir.setText("Salir...");
        jMenuItemSalir.addActionListener(formListener);
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBarra.add(jMenuArchivo);

        jMenuEditar.setText("Editar");

        jMenuItemCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCortar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cortar.png"))); // NOI18N
        jMenuItemCortar.setText("Cortar");
        jMenuItemCortar.addActionListener(formListener);
        jMenuEditar.add(jMenuItemCortar);

        jMenuItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/copiar.png"))); // NOI18N
        jMenuItemCopiar.setText("Copiar");
        jMenuItemCopiar.addActionListener(formListener);
        jMenuEditar.add(jMenuItemCopiar);

        jMenuItemPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPegar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pegar.png"))); // NOI18N
        jMenuItemPegar.setText("Pegar");
        jMenuItemPegar.addActionListener(formListener);
        jMenuEditar.add(jMenuItemPegar);

        jMenuBarra.add(jMenuEditar);

        jMenuVer.setText("Ver");

        jCheckBoxMenuItemVerBarraHerramientas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItemVerBarraHerramientas.setSelected(true);
        jCheckBoxMenuItemVerBarraHerramientas.setText("Barra de Herramientas");
        jCheckBoxMenuItemVerBarraHerramientas.addActionListener(formListener);
        jMenuVer.add(jCheckBoxMenuItemVerBarraHerramientas);

        jCheckBoxMenuItemVerBarraMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItemVerBarraMenu.setSelected(true);
        jCheckBoxMenuItemVerBarraMenu.setText("Barra de Utilidades");
        jCheckBoxMenuItemVerBarraMenu.addActionListener(formListener);
        jMenuVer.add(jCheckBoxMenuItemVerBarraMenu);

        jCheckBoxMenuItemVerBarraEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItemVerBarraEstado.setSelected(true);
        jCheckBoxMenuItemVerBarraEstado.setText("Barra de Estado");
        jCheckBoxMenuItemVerBarraEstado.addActionListener(formListener);
        jMenuVer.add(jCheckBoxMenuItemVerBarraEstado);
        jMenuVer.add(jSeparator1);

        jCheckBoxMenuItemPantallaCompleta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItemPantallaCompleta.setText("Pantalla Completa");
        jCheckBoxMenuItemPantallaCompleta.addActionListener(formListener);
        jMenuVer.add(jCheckBoxMenuItemPantallaCompleta);

        jMenuBarra.add(jMenuVer);

        jMenu1.setText("Ayuda");

        jMenuItemAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/acerca.png"))); // NOI18N
        jMenuItemAyuda.setText("Acerca de...");
        jMenuItemAyuda.addActionListener(formListener);
        jMenu1.add(jMenuItemAyuda);

        jMenuBarra.add(jMenu1);

        setJMenuBar(jMenuBarra);

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener, java.awt.event.MouseWheelListener, javax.swing.event.ChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jToggleButtonPunto) {
                VentanaPrincipal.this.jToggleButtonPuntoActionPerformed(evt);
            }
            else if (evt.getSource() == jToggleButtonLinea) {
                VentanaPrincipal.this.jToggleButtonLineaActionPerformed(evt);
            }
            else if (evt.getSource() == jToggleButtonRectangulo) {
                VentanaPrincipal.this.jToggleButtonRectanguloActionPerformed(evt);
            }
            else if (evt.getSource() == jToggleButtonCirculo) {
                VentanaPrincipal.this.jToggleButtonCirculoActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonNegro) {
                VentanaPrincipal.this.jButtonNegroActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonBlanco) {
                VentanaPrincipal.this.jButtonBlancoActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonRojo) {
                VentanaPrincipal.this.jButtonRojoActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonVerde) {
                VentanaPrincipal.this.jButtonVerdeActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonAzul) {
                VentanaPrincipal.this.jButtonAzulActionPerformed(evt);
            }
            else if (evt.getSource() == jButtonAmarillo) {
                VentanaPrincipal.this.jButtonAmarilloActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxRelleno) {
                VentanaPrincipal.this.jCheckBoxRellenoActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemNuevo) {
                VentanaPrincipal.this.jMenuItemNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemAbrir) {
                VentanaPrincipal.this.jMenuItemAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemGuardar) {
                VentanaPrincipal.this.jMenuItemGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemSalir) {
                VentanaPrincipal.this.jMenuItemSalirActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemCortar) {
                VentanaPrincipal.this.jMenuItemCortarActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemCopiar) {
                VentanaPrincipal.this.jMenuItemCopiarActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemPegar) {
                VentanaPrincipal.this.jMenuItemPegarActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxMenuItemVerBarraHerramientas) {
                VentanaPrincipal.this.jCheckBoxMenuItemVerBarraHerramientasActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxMenuItemVerBarraMenu) {
                VentanaPrincipal.this.jCheckBoxMenuItemVerBarraMenuActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxMenuItemVerBarraEstado) {
                VentanaPrincipal.this.jCheckBoxMenuItemVerBarraEstadoActionPerformed(evt);
            }
            else if (evt.getSource() == jCheckBoxMenuItemPantallaCompleta) {
                VentanaPrincipal.this.jCheckBoxMenuItemPantallaCompletaActionPerformed(evt);
            }
            else if (evt.getSource() == jMenuItemAyuda) {
                VentanaPrincipal.this.jMenuItemAyudaActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jPanelLienzo) {
                VentanaPrincipal.this.jPanelLienzoMousePressed(evt);
            }
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jPanelLienzo) {
                VentanaPrincipal.this.jPanelLienzoMouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }

        public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
            if (evt.getSource() == jLabelGrosorEtiqueta) {
                VentanaPrincipal.this.jLabelGrosorEtiquetaMouseWheelMoved(evt);
            }
            else if (evt.getSource() == jLabelGrosor) {
                VentanaPrincipal.this.jLabelGrosorMouseWheelMoved(evt);
            }
            else if (evt.getSource() == jSliderGrosor) {
                VentanaPrincipal.this.jSliderGrosorMouseWheelMoved(evt);
            }
        }

        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (evt.getSource() == jSliderGrosor) {
                VentanaPrincipal.this.jSliderGrosorStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        jToggleButtonPunto.setSelected(true);
        this.jPanelLienzo.setBegin(null);
        repaint();
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCortarActionPerformed

    private void jMenuItemCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCopiarActionPerformed

    private void jMenuItemPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPegarActionPerformed

    private void jCheckBoxMenuItemVerBarraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemVerBarraMenuActionPerformed
        this.jPanelUtils.setVisible(this.jCheckBoxMenuItemVerBarraMenu.isSelected());
    }//GEN-LAST:event_jCheckBoxMenuItemVerBarraMenuActionPerformed

    private void jCheckBoxMenuItemVerBarraHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemVerBarraHerramientasActionPerformed
        this.jToolBarTools.setVisible(this.jCheckBoxMenuItemVerBarraHerramientas.isSelected());
    }//GEN-LAST:event_jCheckBoxMenuItemVerBarraHerramientasActionPerformed

    private void jCheckBoxMenuItemVerBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemVerBarraEstadoActionPerformed
        this.jPanelStatusBar.setVisible(this.jCheckBoxMenuItemVerBarraEstado.isSelected());
    }//GEN-LAST:event_jCheckBoxMenuItemVerBarraEstadoActionPerformed

    private void jCheckBoxMenuItemPantallaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemPantallaCompletaActionPerformed
        this.jCheckBoxMenuItemVerBarraMenu.setSelected(!this.jCheckBoxMenuItemVerBarraMenu.isSelected());
        this.jCheckBoxMenuItemVerBarraHerramientas.setSelected(!this.jCheckBoxMenuItemVerBarraHerramientas.isSelected());
        this.jCheckBoxMenuItemVerBarraEstado.setSelected(!this.jCheckBoxMenuItemVerBarraEstado.isSelected());
        this.jPanelUtils.setVisible(this.jCheckBoxMenuItemVerBarraMenu.isSelected());
        this.jToolBarTools.setVisible(this.jCheckBoxMenuItemVerBarraHerramientas.isSelected());
        this.jPanelStatusBar.setVisible(this.jCheckBoxMenuItemVerBarraEstado.isSelected());
        if (this.getExtendedState() == javax.swing.JFrame.NORMAL)
            this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        else
            this.setExtendedState(javax.swing.JFrame.NORMAL);
    }//GEN-LAST:event_jCheckBoxMenuItemPantallaCompletaActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        AcercaDe myAcerca = new AcercaDe(this, true);
        myAcerca.setVisible(true);
    }//GEN-LAST:event_jMenuItemAyudaActionPerformed
    
    private void jSliderGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderGrosorStateChanged
        this.jLabelGrosor.setText("" + this.jSliderGrosor.getValue());
        this.jPanelLienzo.setSize(this.jSliderGrosor.getValue());
    }//GEN-LAST:event_jSliderGrosorStateChanged

    private void jSliderGrosorMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jSliderGrosorMouseWheelMoved
        if (evt.getPreciseWheelRotation() < 0) {
            this.jSliderGrosor.setValue(this.jSliderGrosor.getValue()+1);
            //javax.swing.JOptionPane.showMessageDialog(null, "La ruleta va hacia arriba");
        }else{
            this.jSliderGrosor.setValue(this.jSliderGrosor.getValue()-1);
            //javax.swing.JOptionPane.showMessageDialog(null, "La ruleta va hacia abajo");
        }
    }//GEN-LAST:event_jSliderGrosorMouseWheelMoved
    
    private void jLabelGrosorEtiquetaMouseWheelMoved(MouseWheelEvent evt) {//GEN-FIRST:event_jLabelGrosorEtiquetaMouseWheelMoved
        if (evt.getPreciseWheelRotation() < 0) {
            this.jSliderGrosor.setValue(this.jSliderGrosor.getValue()+1);
            //javax.swing.JOptionPane.showMessageDialog(null, "La ruleta va hacia arriba");
        }else{
            this.jSliderGrosor.setValue(this.jSliderGrosor.getValue()-1);
            //javax.swing.JOptionPane.showMessageDialog(null, "La ruleta va hacia abajo");
        }
    }//GEN-LAST:event_jLabelGrosorEtiquetaMouseWheelMoved

    private void jLabelGrosorMouseWheelMoved(MouseWheelEvent evt) {//GEN-FIRST:event_jLabelGrosorMouseWheelMoved
        if (evt.getPreciseWheelRotation() < 0) {
            this.jSliderGrosor.setValue(this.jSliderGrosor.getValue()+1);
            //javax.swing.JOptionPane.showMessageDialog(null, "La ruleta va hacia arriba");
        }else{
            this.jSliderGrosor.setValue(this.jSliderGrosor.getValue()-1);
            //javax.swing.JOptionPane.showMessageDialog(null, "La ruleta va hacia abajo");
        }
    }//GEN-LAST:event_jLabelGrosorMouseWheelMoved
    
    private void jToggleButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPuntoActionPerformed
        this.jPanelLienzo.setTool("point");
        this.jLabelHerramienta.setText("Herramienta: Punto");
    }//GEN-LAST:event_jToggleButtonPuntoActionPerformed

    private void jToggleButtonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLineaActionPerformed
        this.jPanelLienzo.setTool("line");
        this.jLabelHerramienta.setText("Herramienta: Linea");
    }//GEN-LAST:event_jToggleButtonLineaActionPerformed

    private void jToggleButtonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRectanguloActionPerformed
        this.jPanelLienzo.setTool("rect");
        this.jLabelHerramienta.setText("Herramienta: Rectángulo");
    }//GEN-LAST:event_jToggleButtonRectanguloActionPerformed

    private void jToggleButtonCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCirculoActionPerformed
        this.jPanelLienzo.setTool("oval");
        this.jLabelHerramienta.setText("Herramienta: Círculo");
    }//GEN-LAST:event_jToggleButtonCirculoActionPerformed

    private void jButtonNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegroActionPerformed
        this.jPanelLienzo.setColor(Color.black);
        this.jLabelColor.setText("Color: Negro");
    }//GEN-LAST:event_jButtonNegroActionPerformed

    private void jButtonBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlancoActionPerformed
        this.jPanelLienzo.setColor(Color.white);
        this.jLabelColor.setText("Color: Blanco");
    }//GEN-LAST:event_jButtonBlancoActionPerformed

    private void jButtonRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRojoActionPerformed
        this.jPanelLienzo.setColor(Color.red);
        this.jLabelColor.setText("Color: Rojo");
    }//GEN-LAST:event_jButtonRojoActionPerformed

    private void jButtonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerdeActionPerformed
        this.jPanelLienzo.setColor(Color.green);
        this.jLabelColor.setText("Color: Verde");
    }//GEN-LAST:event_jButtonVerdeActionPerformed

    private void jButtonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzulActionPerformed
        this.jPanelLienzo.setColor(Color.blue);
        this.jLabelColor.setText("Color: Azul");
    }//GEN-LAST:event_jButtonAzulActionPerformed

    private void jButtonAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmarilloActionPerformed
        this.jPanelLienzo.setColor(Color.yellow);
        this.jLabelColor.setText("Color: Amarillo");
    }//GEN-LAST:event_jButtonAmarilloActionPerformed

    private void jPanelLienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLienzoMousePressed
        this.jPanelLienzo.setBegin(evt.getPoint());
        repaint();
    }//GEN-LAST:event_jPanelLienzoMousePressed

    private void jPanelLienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLienzoMouseDragged
        this.jPanelLienzo.setEnd(evt.getPoint());
        repaint();
    }//GEN-LAST:event_jPanelLienzoMouseDragged

    private void jCheckBoxRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRellenoActionPerformed
        this.jPanelLienzo.setFill(this.jCheckBoxRelleno.isSelected());
        //javax.swing.JOptionPane.showMessageDialog(null, "hemos pulsado las teclas CTRL+ALT+M");
    }//GEN-LAST:event_jCheckBoxRellenoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupTools;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButtonAmarillo;
    private javax.swing.JButton jButtonAzul;
    private javax.swing.JButton jButtonBlanco;
    private javax.swing.JButton jButtonNegro;
    private javax.swing.JButton jButtonRojo;
    private javax.swing.JButton jButtonVerde;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemPantallaCompleta;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemVerBarraEstado;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemVerBarraHerramientas;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemVerBarraMenu;
    private javax.swing.JCheckBox jCheckBoxRelleno;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelGrosor;
    private javax.swing.JLabel jLabelGrosorEtiqueta;
    private javax.swing.JLabel jLabelHerramienta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemCopiar;
    private javax.swing.JMenuItem jMenuItemCortar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenuItem jMenuItemPegar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuVer;
    private javax.swing.JPanel jPanelCenter;
    private practica4.Lienzo jPanelLienzo;
    private javax.swing.JPanel jPanelStatusBar;
    private javax.swing.JPanel jPanelUtils;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator1MArchivo;
    private javax.swing.JSlider jSliderGrosor;
    private javax.swing.JToggleButton jToggleButtonCirculo;
    private javax.swing.JToggleButton jToggleButtonLinea;
    private javax.swing.JToggleButton jToggleButtonPunto;
    private javax.swing.JToggleButton jToggleButtonRectangulo;
    private javax.swing.JToolBar jToolBarTools;
    // End of variables declaration//GEN-END:variables
}
